/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.template;

import java.net.URL;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application
{
    private int width = 800;
    private int height = 800;
    private VBox root;
    private PageManager pageManager;
    private VBox pageRoot;
    private final int minWidth = 600;
    private final int minHeight = 600;
    private Boolean fullscreen = false;
    private Stage primaryStage;
    private Scene scene;

    public static App app;

    @Override
    public void start(Stage primaryStage) throws Exception
    {      
        app = this;
        // set the minimum width of the primary stage
        this.primaryStage = primaryStage;
        primaryStage.setMinWidth(minWidth);
        primaryStage.setMinHeight(minHeight);

        // get rid of the annoying fullscreen exit hint
        primaryStage.setFullScreenExitHint("");

        // load all sprites
        SpriteManager.loadSprites("src/main/resources/assets/sprites");

        // the basic layout on top of which all separate scenes will be added
        root = new VBox();
        pageRoot = new VBox();

        root.getStyleClass().add("root");

        root.getChildren().add(pageRoot);
        pageRoot.getStyleClass().add("page");

        // make sure that the pageRoot takes up the entire space of the root
        pageRoot.prefWidthProperty().bind(root.widthProperty());
        pageRoot.prefHeightProperty().bind(root.heightProperty());

        // we never touch this aferwards hopefully
        scene = new Scene(root, width, height);

        // the scene manager will help us switch between different scenes
        pageManager = new PageManager(pageRoot);

        Page mainMenu = new MainMenu("menu", pageManager);
        pageManager.addPage(mainMenu);
        pageManager.addPage(new GamePage("game", pageManager));
        pageManager.addPage(new PauseMenu("pause", pageManager));
        pageManager.addPage(new OptionsMenu("options", pageManager));

        // add the stylesheet to the project
        URL styleURL = getClass().getResource("/style.css");
        String stylesheet = styleURL.toExternalForm();
        scene.getStylesheets().add(stylesheet);
        
        // name the project
        primaryStage.setTitle("sokoban");
        primaryStage.setScene(scene);

        primaryStage.show();

        primaryStage.setOnCloseRequest(event -> {
            System.out.println("Closing the game");
        });

    }

    public static void main(String[] args) 
    {
        launch(args);
    }

    public Scene getScene() {
        return scene;
    }

    public Boolean getFullscreen() {
        return fullscreen;
    }
    public void setFullscreen(Boolean fullscreen) {
        this.fullscreen = fullscreen;
        if (fullscreen) {
            primaryStage.setFullScreen(true);
        } else {
            primaryStage.setFullScreen(false);
        }
    }
}
