/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.template;

import java.net.URL;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application
{
    private int width = 800;
    private int height = 800;
    private StackPane root;
    private PageManager pageManager;

    @Override
    public void start(Stage primaryStage) throws Exception
    {   
        // the basic layout on top of which all separate scenes will be added
        root = new StackPane();

        // we never touch this aferwards hopefully
        Scene scene = new Scene(root, width, height);

        // the scene manager will help us switch between different scenes
        pageManager = new PageManager(root);

        Page mainMenu = new Page(new VBox(), "mainMenu", pageManager);
        pageManager.addPage(mainMenu);

        // add the stylesheet to the project
        URL styleURL = getClass().getResource("/style.css");
        String stylesheet = styleURL.toExternalForm();
        scene.getStylesheets().add(stylesheet);
        
        // name the project
        primaryStage.setTitle("sokoban");
        primaryStage.setScene(scene);

        primaryStage.show();

        primaryStage.setOnCloseRequest(event -> {
            System.out.println("oncloserequest");
        });

    }

    public static void main(String[] args) 
    {
        launch(args);
    }
}
